name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.x'
          architecture: 'x64'

      - name: Update pip
        run: pip install -U pip setuptools wheel

      - name: Install dependencies
        run: 'pip install -e .[test]'

      - name: Run tests
        run: pytest --cov=mids tests

      - name: Run coveralls
        uses: coverallsapp/github-action@v2
